### ISSUE TITLE
加载时报错

### ISSUE THREAD

**Issue by hakureireimusama** [KafCoppelia/nonebot_plugin_what2eat#34]
```
05-02 21:16:25 [WARNING] nonebot_plugin_what2eat | What2eat text resource missing! Please check!
05-02 21:16:25 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_what2eat\config.py", line 240, in what2eat_check
    await eating_check()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_what2eat\config.py", line 77, in eating_check
    raise ResourceError("Missing necessary resource: eating.json!")
nonebot_plugin_what2eat.config.ResourceError: Missing necessary resource: eating.json!

05-02 21:16:25 [ERROR] uvicorn | Application startup failed. Exiting.
05-02 21:16:25 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-05-02 21:16:25 CST], next run at: 2023-05-02 21:16:25 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 28, in dy_sched
    await asyncio.sleep(1)
  File "C:\Users\hakurei\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
```

**Comment by KafCoppelia** [comment]
> nonebot_plugin_what2eat.config.ResourceError: Missing necessary resource: eating.json!
